spring:
  application:
    name: techVault

  datasource:
    url: jdbc:postgresql://localhost:5432/techvaultdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

server:
  port: 8080